/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.inicio;

import control.Juego;
import gui.ventanaPrincipal.VentanaPrincipal;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private Image imagenFondo;
    private Image imagenLogo;
    
    public void setImagenes() {
        try {
            this.imagenFondo = ImageIO.read(new File("imagenes\\menuInicio\\inicio.jpg"));
            this.imagenLogo = ImageIO.read(new File("imagenes\\icono\\logo.png"));
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen", "Error con la imagen", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        setImagenes();
        initComponents();
        setSize(1080, 720);
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(imagenLogo); // Establece el icono de la ventana después de initComponents()

    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };
        bIniciarJuego = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();
        bArchivos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exorcista de las profundidades");
        setAlwaysOnTop(true);

        bIniciarJuego.setBackground(new java.awt.Color(0, 0, 0));
        bIniciarJuego.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bIniciarJuego.setForeground(new java.awt.Color(255, 255, 255));
        bIniciarJuego.setText("Iniciar Juego");
        bIniciarJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarJuegoActionPerformed(evt);
            }
        });

        bCerrar.setBackground(new java.awt.Color(0, 0, 0));
        bCerrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bCerrar.setForeground(new java.awt.Color(255, 255, 255));
        bCerrar.setText("Cerrar");
        bCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });

        bArchivos.setBackground(new java.awt.Color(0, 0, 0));
        bArchivos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bArchivos.setForeground(new java.awt.Color(255, 255, 255));
        bArchivos.setText("Cargar Archivos");
        bArchivos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArchivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(483, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bCerrar)
                        .addGap(497, 497, 497))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bIniciarJuego)
                        .addGap(474, 474, 474))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bArchivos)
                        .addGap(461, 461, 461))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(bIniciarJuego)
                .addGap(70, 70, 70)
                .addComponent(bArchivos)
                .addGap(65, 65, 65)
                .addComponent(bCerrar)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarJuegoActionPerformed
        VentanaPrincipal ventana = new VentanaPrincipal();
                
        Juego juego = null;
        try {
            juego = new Juego();
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar la imagen", "Error en imagen", JOptionPane.ERROR_MESSAGE);
            
        }
        
        ventana.setJuego(juego);
                
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_bIniciarJuegoActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bCerrarActionPerformed

    private void bArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArchivosActionPerformed
        DialogoCarpetaArchivos dialogo = new DialogoCarpetaArchivos(this, false);   //Si es modal, para pruebas esta en false RECORDAR CAMBIARLO
        dialogo.setVisible(true);
    }//GEN-LAST:event_bArchivosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bArchivos;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bIniciarJuego;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
