/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.inicio;

import control.Juego;
import gui.ventanaPrincipal.VentanaPrincipal;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private Image imagenFondo;

    public void setImagenFondo() {
        try {
            this.imagenFondo = ImageIO.read(new File("C:\\Users\\Alejandro\\source\\repos\\El-Exorcista-de-las-profundidades\\Exorcista\\src\\imagenes\\menuInicio\\inicio.jpg"));
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen", "Error con la imagen", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        setImagenFondo();
        initComponents();
        setSize(1080, 720);
        setResizable(false);
        setLocationRelativeTo(null);

    }
    
    @Override
    public void paint(Graphics g) {
        g.drawImage(imagenFondo, 0, 0, Color.DARK_GRAY, null);
        System.out.println("re");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bIniciarJuego = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buenas");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        bIniciarJuego.setBackground(new java.awt.Color(0, 0, 0));
        bIniciarJuego.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bIniciarJuego.setForeground(new java.awt.Color(255, 255, 255));
        bIniciarJuego.setText("Iniciar Juego");
        bIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarJuegoActionPerformed(evt);
            }
        });

        bCerrar.setBackground(new java.awt.Color(0, 0, 0));
        bCerrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bCerrar.setForeground(new java.awt.Color(255, 255, 255));
        bCerrar.setText("Cerrar");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bIniciarJuego)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(bCerrar)))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(bIniciarJuego)
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(bCerrar)
                .addGap(195, 195, 195))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarJuegoActionPerformed
        VentanaPrincipal ventana = new VentanaPrincipal();
                
        Juego juego = null;
        try {
            juego = new Juego();
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar la imagen", "Error en imagen", JOptionPane.ERROR_MESSAGE);
            
        }
        
        ventana.setJuego(juego);
                
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_bIniciarJuegoActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bIniciarJuego;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
